title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
username: Mauricio Urraco
user_description: >-
  I'm a Software Engineer from Argentina, always searching for the next
  challenge; no task is too scary nor too difficult. Lately I have been immersed
  in world of Giving Circles working with Grapevine, a California based startup
  trying to improve the world through collaborative giving. I'm the first
  engineer they hired to work on the platform.
user_title: Software Engineer
email: mauriurraco@gmail.com
exclude:
  - package.json
  - src
  - node_modules
baseurl: ''
url: ''
